### ISSUE TITLE
may be setTags function has to support concurrent safe

### ISSUE THREAD

**Issue by erberry** [eko/gocache#21]
may be setTags function has to support concurrent safe

**Comment by Magomogo** [comment]
Yes, probably it should, I've hit this issue:

```
 fatal error: concurrent map read and map write
 goroutine 197173 [running]:
 runtime.throw(0xbdaa97, 0x21)
         /usr/local/lib/go1.16.4/src/runtime/panic.go:1117 +0x72 fp=0xc0157fc5b8 sp=0xc0157fc588 pc=0x438af2
 runtime.mapaccess2_faststr(0xb0a560, 0xc01015c0c0, 0xc011b6c738, 0x15, 0xc0157fc698, 0xb0a560)
         /usr/local/lib/go1.16.4/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc0157fc628 sp=0xc0157fc5b8 pc=0x415e25
 github.com/eko/gocache/v2/store.(*GoCacheStore).setTags(0xc00000f6e0, 0xc9a9d0, 0xc0001b4110, 0xae1940, 0xc01561b060, 0xc01685ca80, 0x3, 0x3)
         /home/developer/go/pkg/mod/github.com/eko/gocache/v2@v2.2.0/store/go_cache.go:92 +0x1a8 fp=0xc0157fc6c8 sp=0xc0157fc628 pc=0x7cca88
 github.com/eko/gocache/v2/store.(*GoCacheStore).Set(0xc00000f6e0, 0xc9a9d0, 0xc0001b4110, 0xae1940, 0xc01561b060, 0xb3cf40, 0xc01685cae0, 0xc01685cab0, 0x30, 0xc000601400)
         /home/developer/go/pkg/mod/github.com/eko/gocache/v2@v2.2.0/store/go_cache.go:76 +0x18b fp=0xc0157fc768 sp=0xc0157fc6c8 pc=0x7cc88b
 github.com/eko/gocache/v2/codec.(*Codec).Set(0xc000033bc0, 0xc9a9d0, 0xc0001b4110, 0xae1940, 0xc01561b060, 0xb3cf40, 0xc01685cae0, 0xc01685cab0, 0x0, 0x0)
         /home/developer/go/pkg/mod/github.com/eko/gocache/v2@v2.2.0/codec/codec.go:73 +0xbb fp=0xc0157fc800 sp=0xc0157fc768 pc=0x7cd6fb
 github.com/eko/gocache/v2/cache.(*Cache).Set(0xc00007bec0, 0xc9a9d0, 0xc0001b4110, 0xae1940, 0xc01561b050, 0xb3cf40, 0xc01685cae0, 0xc01685cab0, 0x1, 0xc00b8d4fa8)
         /home/developer/go/pkg/mod/github.com/eko/gocache/v2@v2.2.0/cache/cache.go:50 +0xc5 fp=0xc0157fc860 sp=0xc0157fc800 pc=0x8df6c5
```

**Comment by Magomogo** [comment]
https://github.com/eko/gocache/pull/138

**Comment by eko** [comment]
This issue is now fixed, closing it. Thank you!
